swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Onlineorder Swagger'
  description: >-
    A simple example of online order server using swagger-2.0           
    specification
  termsOfService: 'http://swagger.io.terms/'
  contact:
    name: 'Cloudmesh-Community-hid-sp18-415'
    email: 'janumudvari@github.com'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/'
    
host: 'localhost:8080'
basePath: '/api'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: orderinfo
    description: Retrieve online order infos
paths:
  /orderinfo:
    post:
      summary: Add new orderinfo
      operationId: add_orderinfo
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: orderinfo
          schema:
            $ref: '#/definitions/OrderInfo'
      responses:
        '200':
          description: Successful order
  /orderinfo/{orderid}:
    get:
      description: retrieve order by orderid
      operationId: find_orderinfo_orderid_get
      produces:
            - "application/json"
      parameters:
        - in: path
          name: orderid
          description: orderid for order to be retrieved
          required: true
          type: integer
      responses:
        '200':
          description: successful output
          schema:
            $ref: '#/definitions/OrderInfo'
definitions:
  OrderInfo:
    type: object
    properties:
      id: 
        type: integer
      location:
        type: string
    required:
      - orderid
      - orderlocation  

