swagger: '2.0'
info:
  version: 0.0.1
  title: User Identity
  description: >-
    A swagger service to get service user identity using swagger-2.0
    specification
  termsOfService: 'http://swagger.io.terms/'
  contact:
    name: Cloudmesh-Community-hid-sp18-415
    email: janumudvari@github.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /cloudmesh/identity/
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Identity
    description: Retrieve user ID
paths:
  /Identity:
    get:
      summary: User identification
      description: 'Return user identity'
      parameters:
        - in: query
          name: ID
          description: user id
          required: true
          type: integer
        - in: query
          name: username
          description: username
          required: true
          type: string
      responses:
        '200':
          description: successful output
          schema:
            $ref: '#/definitions/UserIdentity'
definitions:
  UserIdentity:
    type: object
    properties:
      ID:
        type: integer
      username:
        type: string
    required:
      - ID
      - username

